/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 936c033cbd0c9b7418ea5e68ea2e2508)
interface __BaseEnv_Env {
	STORAGE?: R2Bucket;
	DB: D1Database;
	ASSETS: Fetcher;
	NEXT_PUBLIC_ENV?: "preview";
	NEXT_PUBLIC_SITE_URL?: "https://kclmc-platform-preview.workers.dev";
	SUPERADMIN_EMAIL: string;
	COMMITTEE_EMAILS: string;
	NEXT_PUBLIC_SUPABASE_URL: string;
	NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
	SUPABASE_SERVICE_ROLE_KEY: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./.open-next/worker");
	}
	interface PreviewEnv {
		STORAGE: R2Bucket;
		DB: D1Database;
		ASSETS: Fetcher;
		NEXT_PUBLIC_ENV: "preview";
		NEXT_PUBLIC_SITE_URL: "https://kclmc-platform-preview.workers.dev";
		SUPERADMIN_EMAIL: string;
		COMMITTEE_EMAILS: string;
		NEXT_PUBLIC_SUPABASE_URL: string;
		NEXT_PUBLIC_SUPABASE_ANON_KEY: string;
		SUPABASE_SERVICE_ROLE_KEY: string;
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "NEXT_PUBLIC_ENV" | "NEXT_PUBLIC_SITE_URL" | "SUPERADMIN_EMAIL" | "COMMITTEE_EMAILS" | "NEXT_PUBLIC_SUPABASE_URL" | "NEXT_PUBLIC_SUPABASE_ANON_KEY" | "SUPABASE_SERVICE_ROLE_KEY">> {}
}
